### ISSUE TITLE
npm run build ==>  Cannot read properties of undefined (reading 'views')

### ISSUE THREAD

**Issue by zigomi** [one-aalam/astro-ink#48]
```
$ npm run build

[.......]

▶ src/pages/blog/teat.md
 error   Cannot read properties of undefined (reading 'views')
  File:
    async file:///home/me/astro-ink__dev/node_modules/astro/dist/runtime/server/render/astro/render.js:70:11
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'views')
    at Object.default (file:///home/me/astro-ink__dev/dist/chunks/pages/_slug__62e5e4f6.mjs:559:156)
    at new AstroComponentInstance (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:989:32)
    at createAstroComponentInstance (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:1027:20)
    at renderAstroComponent (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:1449:20)
    at renderComponent (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:1468:12)
    at file:///home/me/astro-ink__dev/dist/chunks/pages/_slug__62e5e4f6.mjs:558:270
    at AstroComponentInstance.post [as factory] (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:199:12)
    at AstroComponentInstance.init (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:996:29)
    at AstroComponentInstance.render (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:1001:18)
    at Object.render (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:1452:22)
    at renderChild (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:959:17)
    at async Object.renderToFinalDestination (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:775:7)
    at async RenderTemplateResult.render (file:///home/me/astro-ink__dev/dist/chunks/astro_646f7050.mjs:1071:9)
    at async file:///home/me/astro-ink__dev/node_modules/astro/dist/runtime/server/render/astro/render.js:70:11

error: script "build" exited with code 1 (SIGHUP)

```

I run it locally via npm with no issue, and I'd patched a bug with port number. 

How to fix this?

**Comment by one-aalam** [comment]
Hi, @zigomi Can you confirm if you have a [`.env`](https://github.com/one-aalam/astro-ink/blob/main/.env.example) file for your setup, and pre-populated with at least the `SITE_URI` value? 

You can check https://github.com/one-aalam/astro-ink/issues/45 for reference

**Comment by zigomi** [comment]
@one-aalam yes.
