### ISSUE TITLE
`npm run preview` not supported

### ISSUE THREAD

**Issue by dandv** [one-aalam/astro-ink#61]
```
$ npx degit one-aalam/astro-ink
...
$ npm install
...
$ npm run build
... <no errors so far>
$ npm run preview

> astro-ink@2.0.0 preview
> astro preview

[preview] The @astrojs/vercel/serverless adapter does not support the preview command.
  Stack trace:
    at preview (file:///home/dandv/astro-ink/node_modules/astro/dist/core/preview/index.js:31:11)
    at async runCommand (file:///home/dandv/astro-ink/node_modules/astro/dist/cli/index.js:129:22)
```

Is this expected?

**Comment by one-aalam** [comment]
Hey @dandv If you're using Astro(and Ink) for static builds try removing the adapter here: https://github.com/one-aalam/astro-ink/blob/main/astro.config.mjs#L55 

For server side support, if you want local previews try https://docs.astro.build/en/guides/integrations-guide/node/ 

Closing the issue. If you still have some issue with this, please feel free to report.
